name: First WF

on: push

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1.1
        uses: actions/checkout@v4
      - name: Step 1.2
        run: env | sort
  
  job2:
    name: Second Job
    runs-on: ubuntu-latest
    steps:
      - name: Step 2.1
        uses: actions/checkout@v4
      - name: Step 2.2
        run: env | sort

